#ifndef _K2OPT_CONFIG_H
#define _K2OPT_CONFIG_H

#define HAVE_Z_LIB
#define HAVE_PNG_LIB
#define HAVE_JPEG_LIB
#define HAVE_DJVU_LIB
#define HAVE_MUPDF_LIB
#define HAVE_LEPTONICA_LIB
#define HAVE_TESSERACT_LIB

#undef DHAVE_JASPER_LIB
#undef DHAVE_GSL_LIB
#undef DHAVE_GHOSTSCRIPT
#undef DHAVE_GOCR_LIB

#endif
